name: app_ewally
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: 0.5.12+4
  dio: 3.0.10
  bloc_pattern: 1.5.2
  rxdart: 0.24.1
  google_fonts: 1.1.1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any

flutter:

  uses-material-design: true